apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: salimovanusher6@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "prod.anushervon.life"
      dns01:
        route53:
          region: us-east-2
          accessKeyID: AKIA4MTWJP3XVF74SNL3
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key
